source "./adapters/symlink"

install_zshrc() {
  echo ""
  echo "🔧 Setting up .zshrc configuration..."
  install_symlink "$HOME/managed/.zshrc" "$HOME/.zshrc"
}

uninstall_zshrc() {
  echo ""
  echo "🗑️ Removing .zshrc configuration..."
  uninstall_symlink "$HOME/managed/.zshrc" "$HOME/.zshrc"
}
